CREATE TABLE Registration (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    registrationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT(20) NOT NULL,
    course_id BIGINT(20) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES Course(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
